version: '2'
services:
    drugws-app:
        image: drugws
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://drugws-mysql:3306/drugws?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    drugws-mysql:
        extends:
            file: mysql.yml
            service: drugws-mysql
